<body>
    <div id="main-bg"></div>

    <div id="form-center">
        <div id="options">
            <div class="option-wrapper">
                <div class="option">
                    <h2>Don't have an account?</h2>
                    <div class="blue-bit"></div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <button class="btn" onclick="move(0)">Sign up</button>
                </div>
            </div>
            <div class="option-wrapper">
                <div class="option">
                    <h2>Have an account?</h2>
                    <div class="blue-bit"></div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
                    <button class="btn" onclick="move(1)">Login</button>
                </div>
            </div>
        </div>
        <div id="moving-forms">
            <form class="form" action="" id="login">
                <h2>This is a <?php echo $data ?> </h2>
                <div class="blue-bit"></div>
                <div class="logo"></div>
                <div class="input-field">
                    <label>Email</label>
                    <i class="material-icons">mail_outline</i>
                    <span class="red">*</span>
                    <input class="input" type="text" name="username">
                </div>
                <div class="input-field">
                    <label>Password</label>
                    <i class="material-icons">lock_outline</i>
                    <span class="red">*</span>
                    <input class="input" type="password" name="username">
                </div>
                <button class="btn-orng">Login</button>
                <button class="btn-empty">Forgot?</button>
            </form>
            <form class="form" action="" id="signup">
                <h2>Sign up</h2>
                <div class="blue-bit"></div>
                <div class="logo"></div>
                <div class="input-field">
                    <label>Name</label>
                    <i class="material-icons">perm_identity</i>
                    <span class="red">*</span>
                    <input class="input" type="text" name="username">
                </div>
                <div class="input-field">
                    <label>Email</label>
                    <i class="material-icons">mail_outline</i>
                    <span class="red">*</span>
                    <input class="input" type="text" name="username">
                </div>
                <div class="input-field">
                    <label>Password</label>
                    <i class="material-icons">lock</i>
                    <span class="red">*</span>
                    <input class="input" type="password" name="username">
                </div>
                <button class="btn-orng">Login</button>
            </form>
        </div>
        <div id="face"></div>
    </div>

    <footer>
        <h4>All rights reserved "Magebit" 2016.</h4>
    </footer>
    <script src="frontend/js.js"></script>
</body>