<div id="main-bg"></div>
<div id="user-profile">
    <nav>
        <form action="profile/logout" method="post">
            <button type="submit" class="btn-empty">Logout</button>
        </form>
        <h2>

        Welcome, <?php echo $data["user"]["username"] ?>!

        </h2>
        <div class="blue-bit"></div>
        <h3>These are your attributes:</h3>
    </nav>
    <div id="attributes">
        <button class="btn" onclick="showAdd()">+Add</button>

        <?php
            foreach($subviews as $attribute){
                $attribute->render($attribute->data);
            }
        ?>


    </div>
</div>
<div class="edit">
    <button class="btn-empty" onclick="exit('add')">Exit</button>
    <form action="profile/add" method="post">
        <h4>Attribute name:</h4>
        <input type="text" name="attribute_name">
        <h4>Attribute value:</h4>
        <input type="text" name="attribute_value">
        <button class="btn">Add</button>
    </form>
</div>
<div class="edit">
    <button class="btn-empty" onclick="exit('edit')">Exit</button>
    <form action="profile/attribute/edit" method="post">
        <input type="hidden" name="attribute_id" value="" id="edit-attr-id">   
        <h4>Attribute name:</h4>
        <input type="text" name="attribute_name">
        <h4>Attribute value:</h4>
        <input type="text" name="attribute_value">
        <button class="btn" type="submit">Save</button>
    </form>
</div>
<script src="frontend/profile.js"></script>